// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart' show defaultTargetPlatform;
import 'package:flutter/material.dart' show TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A platform-specific options object.
class DefaultFirebaseOptions {
  /// Android options for Firebase Core
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQI8lZ8eN02dpPaqb5pqyl_lLHM5ct_w',
    appId: '1:583737317649:android:b516be2456ced308e594b0',
    messagingSenderId: '583737317649',
    projectId: 'beauty-body-86d4e',
    storageBucket: 'beauty-body-86d4e.firebasestorage.app',
  );

  /// Get the current platform's Firebase options
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
